version: '3.8'
services:
  my_api:
    image: haison19952013/fashion_recsys:v0.0.0  # Adjust the name if needed
    ports:
      - "8000:8000"  # Expose FastAPI on port 8000
    environment:
      - PYTHONPATH=/app:/app/src/training_pipeline
    healthcheck:
      test: ["CMD", "curl", "-f", "http://my_api:8000/healthy_check"]  # Adjust endpoint as needed
      interval: 30s  # Interval between health checks
      timeout: 10s   # Timeout for each check
      retries: 3     # Number of retries before considering the service unhealthy
    networks:
      - my_network  # Connect to the custom network

  my_web:
    image: haison19952013/fashion_recsys_web:v0.0.0  # Adjust the name if needed
    ports:
      - "8501:8501"  # Expose Streamlit on port 8501
    depends_on:
      my_api:
        condition: service_healthy  # Ensure FastAPI is healthy before starting Streamlit
    networks:
      - my_network  # Connect to the custom network

networks:
  my_network:  # Define the custom network
